server:
  port: 8383


turbine:
  appConfig: author,credentials,post,category
  aggregator:
    clusterConfig: AUTHOR,CREDENTIALS,POST,CATEGORY

eureka:
  client:
    region: default
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    region: default
    registryFetchIntervalSeconds : 5
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
      preferIpAddress: true
