server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://localhost/restful_blog_configuration_properties.git
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
           uri: http://${GOGS_PORT_3000_TCP_ADDR}:3000/juanwalker/restful_blog_configuration_properties.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
      hostname: ${EUREKA_PORT_8761_TCP_ADDR:localhost}
      preferIpAddress: true